### ISSUE TITLE
请在 https://gitee.com/y_project/RuoYi-Vue/issues 里提问

### ISSUE THREAD

**Issue by yangzongzhuan** [yangzongzhuan/RuoYi-Vue3#1]
请在[RuoYi-issues](https://gitee.com/y_project/RuoYi-Vue/issues)里提问，方便统一处理。

**Comment by kisshexuxia** [comment]
PS E:\work\RuoYi-Vue3> npm run dev

> ruoyi@3.8.0 dev
> vite

failed to load config from E:\work\RuoYi-Vue3\vite.config.js
error when starting dev server:
Require stack:
- E:\work\RuoYi-Vue3\vite.config.js
- E:\work\RuoYi-Vue3\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js
- E:\work\RuoYi-Vue3\node_modules\vite\dist\node\cli.js
- E:\work\RuoYi-Vue3\node_modules\vite\bin\vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (E:\work\RuoYi-Vue3\vite.config.js:36:30)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.require.extensions.<computed> [as .js] (E:\work\RuoYi-Vue3\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:68713:20)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)

**Comment by sfltd** [comment]
代码会迁移到gitee.com吗？gitee很慢

**Comment by newz-max** [comment]
大佬，我准备给你的项目提交自己写的TS，有兴趣让我贡献代码吗

**Comment by xuehongnizhao** [comment]
请问表单生成部分有计划什么时候上吗

**Comment by huangwenboha563** [comment]
> 打算改成TS的吗，现在好像比较流行TS了

肯定会的，超过vben,vben封装的有点深，估计ruoyi会好一些

**Comment by EELIC** [comment]
> 大佬，我准备给你的项目提交自己写的TS，有兴趣让我贡献代码吗

交流下呗，我也在改TS

**Comment by ifengdu** [comment]
可以出TS版本的吗

**Comment by zzh948498** [comment]
> 可以出TS版本的吗

ts我这里贡献了一版，可供参考
https://github.com/zzh948498/RuoYi-Vue3-ts

**Comment by xuzhitudev** [comment]
请问vue3版本官方何时改造一下，对应Ruoyi-Cloud微服务版本的后台？

**Comment by hhw3KevinHou** [comment]
> 打算改成TS的吗，现在好像比较流行TS了

决绝TS，反对TS。代码量膨胀太多，泛型类型标记根据程序员水平差异太多。还不如原生ES6经典。

**Comment by hhw3KevinHou** [comment]
> > 可以出TS版本的吗
> 
> ts我这里贡献了一版，可供参考 https://github.com/zzh948498/RuoYi-Vue3-ts

鄙视TS，拒绝TS。公司如果要我用TS得加钱。

**Comment by github-cherry** [comment]
> > > 可以出TS版本的吗
> > 
> > 
> > ts我这里贡献了一版，可供参考 https://github.com/zzh948498/RuoYi-Vue3-ts
> 
> 鄙视TS，拒绝TS。公司如果要我用TS得加钱。

哈哈哈哈哈哈，我也是。拒绝内卷

**Comment by amangqq** [comment]
> > > 可以出TS版本的吗
> > 
> > 
> > ts我这里贡献了一版，可供参考 https://github.com/zzh948498/RuoYi-Vue3-ts
> 
> 鄙视TS，拒绝TS。公司如果要我用TS得加钱。

哈哈

**Comment by atearsan** [comment]
> > > > 可以出TS版本的吗
> > > 
> > > 
> > > ts我这里贡献了一版，可供参考 https://github.com/zzh948498/RuoYi-Vue3-ts
> > 
> > 
> > 鄙视TS，拒绝TS。公司如果要我用TS得加钱。
> 
> 哈哈

+1。会js不会ts的太难了。
最近做移动端网页，用之前熟悉的一个脚手架初始化项目，最新版本是ts的，开发完了打包各种报错（`类型“{}”上不存在属性“”。ts-plugin(2339)`），应该跟类型有关。弄了半天又没搞定。
打算直接复制`Ruoyi-Vue3`改一个移动端H5脚手架来。
（——没做过前端的程序员/小产品）

**Comment by js-yangjiabao** [comment]
表单构建的代码啥时候可以上

**Comment by xinmingG** [comment]
若依vue3版本会出现丢失路由数据的情况，getRouters 返回的数据有时会缺少自己新增的菜单路由，多刷新几次又正常了，请各位大佬解惑一下

**Comment by sgshy1995** [comment]
> 若依vue3版本会出现丢失路由数据的情况，getRouters 返回的数据有时会缺少自己新增的菜单路由，多刷新几次又正常了，请各位大佬解惑一下

可以看一下接口，有时候返回的菜单就是少的，应该是后端的bug

**Comment by sgshy1995** [comment]
> 若依vue3版本会出现丢失路由数据的情况，getRouters 返回的数据有时会缺少自己新增的菜单路由，多刷新几次又正常了，请各位大佬解惑一下

当时用vue2也有此问题

**Comment by elarbor** [comment]
> 代码会迁移到gitee.com吗？github很慢

下载个 [Watt Toolkit](https://steampp.net/) 挺不错。还是[开源](https://github.com/BeyondDimension/SteamTools)的呢
