### ISSUE TITLE
yarn dev项目跑不起来？

### ISSUE THREAD

**Issue by abg2019** [yangzongzhuan/RuoYi-Vue3#126]
VITE v3.2.3  ready in 1726 ms

  ➜  Local:   http://localhost:80/
  ➜  Network: http://192.168.161.1:80/
  ➜  Network: http://192.168.72.1:80/
  ➜  Network: http://192.168.1.102:80/
[postcss] Failed to obtain root from "c:\wwwroot\html\RuoYi-Vue3".
[postcss] Failed to obtain root from "c:\wwwroot\html\RuoYi-Vue3". (x2)
[postcss] Failed to obtain root from "c:\wwwroot\html\RuoYi-Vue3". (x3)
22:23:07 [vite] Internal server error: [postcss] Failed to obtain root from "c:\wwwroot\html\RuoYi-Vue3".
  Plugin: vite:css
  File: c:/wwwroot/html/RuoYi-Vue3/src/assets/styles/variables.module.scss:undefined:undefined
      at new FileSystemLoader (file:///c:/wwwroot/html/RuoYi-Vue3/node_modules/vite/dist/node/chunks/dep-7591464a.js:1582:15)
      at getLoader (file:///c:/wwwroot/html/RuoYi-Vue3/node_modules/vite/dist/node/chunks/dep-7591464a.js:7409:79)
      at OnceExit (file:///c:/wwwroot/html/RuoYi-Vue3/node_modules/vite/dist/node/chunks/dep-7591464a.js:7463:22)
      at LazyResult.runAsync (c:\wwwroot\html\RuoYi-Vue3\node_modules\vite\node_modules\postcss\lib\lazy-result.js:433:21)
      at LazyResult.async (c:\wwwroot\html\RuoYi-Vue3\node_modules\vite\node_modules\postcss\lib\lazy-result.js:221:30)
      at LazyResult.then (c:\wwwroot\html\RuoYi-Vue3\node_modules\vite\node_modules\postcss\lib\lazy-result.js:206:17)

**Comment by ylka** [comment]
the same

**Comment by jtailiang** [comment]
我也一样啊

**Comment by ylka** [comment]
单开控制台运行命令不行，在vscode下跑命令又可以

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
