### ISSUE TITLE
克隆项目到本地后，执行启动命令报错

### ISSUE THREAD

**Issue by object360** [yangzongzhuan/RuoYi-Vue3#135]
克隆项目下来后，执行
# 安装依赖
yarn --registry=https://registry.npmmirror.com

# 启动服务
yarn dev

执行启动命令后，报如下错误

yarn run v1.22.19
$ vite
F:\WorkSpace\RuoYi-Vue3\node_modules\vite\bin\vite.js:2
import { performance } from 'node:perf_hooks'
^^^^^^

SyntaxError: Cannot use import statement outside a module
[90m    at Module._compile (internal/modules/cjs/loader.js:891:18)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10
)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:811:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues 需要提供出能复现问题详细步骤。
