### ISSUE TITLE
vue3版本不兼容低版本浏览器，怎么解决一下啊？现在项目中有很多低版本的谷歌浏览器V49等，怎么让vue3兼容呀？

### ISSUE THREAD

**Issue by liuyongfei813** [yangzongzhuan/RuoYi-Vue3#179]
目前这个vue3版本不兼容低版本的浏览器，如谷歌浏览器49以下版本等，打开都是白屏，怎么解决一下啊？

**Comment by Asuancaiyu** [comment]
使用 vite 的插件[ `@vitejs/plugin-legacy` ](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy)；

1. 安装前置依赖 `npm add -D terser`
2. 安装插件 `npm add -D @vitejs/plugin-legacy`
3. `vite.config.js` 中添加配置 :
```
import legacy from '@vitejs/plugin-legacy'

export default {
  plugins: [
    legacy({
      targets: ['defaults', 'not IE 11', 'chrome 48'],
    }),
  ],
}
```
**如果还白屏，要验证index.html中<script nomoduel src='/xxx.js'>的`xxx.js`文件否执行了，这时候要根据情况修改`vite.config.js` 中的 `base: ''`参数,一般base参数我会留空，这样打包的静态资源路径就是以`./`开头的相对路径**。

**Comment by liuyongfei813** [comment]
大神，按照您的方法尝试了一下，index.html中<script nomoduel src='/xxx.js'>的xxx.js文件应该执行执行，但是打开页面出现如下错误：
Unhandled promise rejection ReferenceError: require is not defined
    at new ice (http://192.168.10.9:8056/assets/index-legacy-64b9e936.js:15:742295)
    at new dce (http://192.168.10.9:8056/assets/index-legacy-64b9e936.js:15:745746)
    at new zce (http://192.168.10.9:8056/assets/index-legacy-64b9e936.js:15:777885)
    at Lce.build (http://192.168.10.9:8056/assets/index-legacy-64b9e936.js:15:794813)
    at Object.init (http://192.168.10.9:8056/assets/index-legacy-64b9e936.js:15:795257)
    at System.register.d.execute (http://192.168.10.9:8056/assets/index-legacy-64b9e936.js:47:18647)
    at n (http://192.168.10.9:8056/assets/polyfills-legacy-2438d061.js:1:120111)
    at v (http://192.168.10.9:8056/assets/polyfills-legacy-2438d061.js:1:120485)
    at http://192.168.10.9:8056/assets/polyfills-legacy-2438d061.js:1:120024
    at cU []((http://192.168.10.9:8056/assets/polyfills-legacy-2438d061.js:1:97474)[](url))

**Comment by Asuancaiyu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liuyongfei813** [comment]
![Uploading 微信图片_20230627080337.jpg…]()

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues

**Comment by Asuancaiyu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sunchir** [comment]
"@vitejs/plugin-legacy": "^5.3.2",  "terser": "^5.29.1",    "resize-observer-polyfill": "^1.5.1",  window.ResizeObserver = ResizeObserver

**Comment by Asuancaiyu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
