### ISSUE TITLE
项目打包报错

### ISSUE THREAD

**Issue by LYP857** [yangzongzhuan/RuoYi-Vue3#196]
D:\idea-space\idea-space\digital-earth\RuoYi-Vue3>yarn build:prod                                
    at onRollupWarning (file:///D:/idea-space/idea-space/digital-earth/RuoYi-Vue3/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:45522:19)
    at onwarn (file:///D:/idea-space/idea-space/digital-earth/RuoYi-Vue3/node_modules/vite/dist/node/chunks/dep-51c4f80a.js:45293:13)
    at Object.onwarn (file:///D:/idea-space/idea-space/digital-earth/RuoYi-Vue3/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
    at ModuleLoader.handleResolveId (file:///D:/idea-space/idea-space/digital-earth/RuoYi-Vue3/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
    at file:///D:/idea-space/idea-space/digital-earth/RuoYi-Vue3/node_modules/rollup/dist/es/shared/rollup.js:22119:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

![image](https://github.com/yangzongzhuan/RuoYi-Vue3/assets/100215619/b6bc4ebe-d8da-46a5-aea0-7fdc0250c4f5)

**Comment by yangzongzhuan** [comment]
前后端分离版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Vue/issues
