### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'ids' before initialization

### ISSUE THREAD

**Issue by devzwy** [yangzongzhuan/RuoYi-Vue3#24]
多选bu g

**Comment by devzwy** [comment]
```
[Vue warn]: Unhandled error during execution of component event handler 
  at <ElButton type="danger" plain="" icon="Delete"  ... > 
  at <ElCol span=1.5 > 
  at <ElRow gutter=10 class="mb8" > 
  at <Auth onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > key="/yjjs/auth" > 
  at <KeepAlive include= ['Auth'] > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="fade-transform" mode="out-in" > 
  at <RouterView> 
  at <AppMain> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:6620
logError @ runtime-core.esm-bundler.js:6794
handleError @ runtime-core.esm-bundler.js:6786
callWithErrorHandling @ runtime-core.esm-bundler.js:6740
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
emit$1 @ runtime-core.esm-bundler.js:289
(anonymous) @ runtime-core.esm-bundler.js:6522
handleClick @ button.vue:142
createElementBlock.onClick._cache.<computed>._cache.<computed> @ button.vue?vue&type=template&id=802c5c76&lang.js:20
callWithErrorHandling @ runtime-core.esm-bundler.js:6737
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
invoker @ runtime-dom.esm-bundler.js:357
runtime-core.esm-bundler.js:6620 [Vue warn]: Unhandled error during execution of native event handler 
  at <ElButton type="danger" plain="" icon="Delete"  ... > 
  at <ElCol span=1.5 > 
  at <ElRow gutter=10 class="mb8" > 
  at <Auth onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > key="/yjjs/auth" > 
  at <KeepAlive include= ['Auth'] > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="fade-transform" mode="out-in" > 
  at <RouterView> 
  at <AppMain> 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:6620
logError @ runtime-core.esm-bundler.js:6794
handleError @ runtime-core.esm-bundler.js:6786
callWithErrorHandling @ runtime-core.esm-bundler.js:6740
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
invoker @ runtime-dom.esm-bundler.js:357
runtime-core.esm-bundler.js:6800 Uncaught ReferenceError: Cannot access 'ids' before initialization
    at handleDelete (index.vue?t=1645256663863:321:25)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6737:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6746:21)
    at emit$1 (runtime-core.esm-bundler.js:289:9)
    at runtime-core.esm-bundler.js:6522:53
    at Proxy.handleClick (button.vue:142:7)
    at createElementBlock.onClick._cache.<computed>._cache.<computed> (button.vue?vue&type=template&id=802c5c76&lang.js:20:13)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6737:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6746:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:357:13)
handleDelete @ index.vue?t=1645256663863:321
callWithErrorHandling @ runtime-core.esm-bundler.js:6737
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
emit$1 @ runtime-core.esm-bundler.js:289
(anonymous) @ runtime-core.esm-bundler.js:6522
handleClick @ button.vue:142
createElementBlock.onClick._cache.<computed>._cache.<computed> @ button.vue?vue&type=template&id=802c5c76&lang.js:20
callWithErrorHandling @ runtime-core.esm-bundler.js:6737
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
invoker @ runtime-dom.esm-bundler.js:357
```

**Comment by yangzongzhuan** [comment]
请提供出能复现问题的详细步骤和示例代码。

**Comment by zzvaki** [comment]
应该是列表页面批量删除的方法ids取值的bug，在代码生成vue3的页面里有
`js
/** 删除按钮操作 */
function handleDelete(row) {
  const ids = row.id || ids.value;
  proxy.$modal.confirm('是否确认删除用户车辆信息编号为"' + ids + '"的数据项？').then(function() {
    return delCar(ids);
  }).then(() => {
    getList();
    proxy.$modal.msgSuccess("删除成功");
  }).catch(() => {});
}
`
会报错 Cannot access 'ids' before initialization

RuoYi-Vue的仓库里已有这个issue，传送门：
https://gitee.com/y_project/RuoYi-Vue/issues/I5A1WN
