### ISSUE TITLE
克隆下来，启动失败

### ISSUE THREAD

**Issue by XiaoChen968** [yangzongzhuan/RuoYi-Vue3#28]
(this will be run only when your dependencies or config have changed)
error when starting dev server:
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Server.httpServer.listen (E:\MyTest\RuoYi-Vue3\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:66928:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ruoyi@3.8.1 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ruoyi@3.8.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2022-02-23T07_13_50_194Z-debug.log

**Comment by chun1997** [comment]
vite.config.js 里面把port改成 '8080'

**Comment by yangzongzhuan** [comment]
Error: listen EACCES: permission denied 0.0.0.0:80  80端口你没有权限，可以换一下再试。
