### ISSUE TITLE
按照指令执行yarn --registry=https://registry.npmmirror.com后，执行npm run dev报以下错误

### ISSUE THREAD

**Issue by 3110474434** [yangzongzhuan/RuoYi-Vue3#46]
Pre-bundling dependencies:
  vue
  js-cookie
  element-plus
  element-plus/lib/locale/lang/zh-cn
  vuex
  (...and 9 more)
(this will be run only when your dependencies or config have changed)
error when starting dev server:
Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1303:21)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1454:7)
    at Server.httpServer.listen (D:\project\center-temp\rouyi-vue\RuoYi-Cloud-Vue3-master\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:66928:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by 3110474434** [comment]
用yarn就好了

**Comment by yangzongzhuan** [comment]
测试是正常的，没有你说的问题。都能启动。不过建议是用yarn。因为你是用yarn去安装的。
